public struct SupportedLanguage {

    public static let ENGLISH_US = "en_US"
    public static let ARABIC = "ar_SA"
    public static let CHINNESE_TAIWAN = "zh_TW"
    public static let FRENCH = "fr_FR"
    public static let GERMAN = "de_DE"
    public static let GREEK = "el_GR"
    public static let INDONESIAN = "in_ID"
    public static let KOREAN = "ko_KR"
    public static let MALAYSIA = "ms_MY"
    public static let POLISH = "pl_PL"
    public static let PORTUGUESE = "pt_PT"
    public static let HINDI = "hi_IN"
    public static let RUSSIAN = "ru_RO"
    public static let ROMANIAN = "ro_RO"
    public static let SWEDISH = "sv_SE"
    public static let VIETNAMESE = "vi_VN"
    public static let TURKISH = "tr_TR"
    public static let CROATIAN = "hr_HR"
    public static let TAGALOG = "tl_PH"
    public static let THAI = "th_TH"
    public static let ITALIAN = "it_IT"
    public static let SPANISH = "es_ES"
    public static let JAPANESE = "ja_JP"
    public static let BENGALI = "bn_IN"
    public static let CHINNESE_CHINA = "zh_CN"
    public static let ENGLISH_BRITISH = "en_rGB"
}
